// Golden vectors for Cloud-room end-to-end encryption (src/lib/rooms/e2e.ts).
// The app's implementation (bishare-flutter lib/features/room/data/room_e2e.dart)
// must reproduce every value byte for byte; its test reads the same JSON.
//
// Run from bishare-web (esbuild because crypto.ts uses TS-only syntax that
// Node's type stripping refuses):
//   npx esbuild tools/room-e2e-vectors.ts --bundle --platform=node --format=esm --log-level=warning | node --input-type=module -           write
//   npx esbuild tools/room-e2e-vectors.ts --bundle --platform=node --format=esm --log-level=warning | node --input-type=module - --check   verify
import fs from "node:fs";
import path from "node:path";
import { x25519 } from "@noble/curves/ed25519.js";
import { b64u, fromB64u, keyId, sealFile, openFile, grant, acceptGrant, fileKeys } from "../src/lib/rooms/e2e.ts";
import { EncryptedSource, importKey, decryptStream } from "../src/lib/e2e/crypto.ts";

const OUT = path.resolve("src/lib/rooms/room-e2e-vectors.json");
const seq = (n: number, start: number) => Uint8Array.from({ length: n }, (_, i) => (start + i) & 0xff);

const roomKey = seq(32, 0x10);
const code = "BX4R";
const salt = seq(16, 0x80);
const metaNonce = seq(12, 0xa0);
const meta = { name: "Résumé 📄 final.pdf", type: "application/pdf", size: 1_234_567, thumbnail: "/9j/4AAQSkZJRg==" };
const joinerPriv = seq(32, 0x40);
const granterPriv = seq(32, 0x60);
const grantNonce = seq(12, 0xc0);
const plaintext = new TextEncoder().encode("BIShare room vector — the bytes a member uploads.\n".repeat(3));
const bse2Salt = seq(4, 0xe0);

async function build() {
  const kid = await keyId(roomKey);
  const sealed = await sealFile(roomKey, meta, salt, metaNonce);
  const { metaKey } = await fileKeys(roomKey, salt);
  const joiner = { priv: joinerPriv, pub: x25519.getPublicKey(joinerPriv) };
  const granter = { priv: granterPriv, pub: x25519.getPublicKey(granterPriv) };
  const box = await grant(roomKey, code, granter, b64u(joiner.pub), grantNonce);
  const src = new EncryptedSource(new File([plaintext], "v.bin"), await importKey(sealed.fileKey), bse2Salt);
  const container = await src.slice(0, src.size);
  return {
    note: "Generated by bishare-web tools/room-e2e-vectors.ts from src/lib/rooms/e2e.ts. Binary values are base64url without padding.",
    roomKey: b64u(roomKey),
    kid,
    file: {
      salt: b64u(salt),
      metaNonce: b64u(metaNonce),
      meta,
      metaJson: JSON.stringify({ n: meta.name, t: meta.type, s: meta.size, th: meta.thumbnail }),
      fileKey: b64u(sealed.fileKey),
      metaKey: b64u(metaKey),
      encMeta: sealed.meta,
      bse2Salt: b64u(bse2Salt),
      plaintext: b64u(plaintext),
      container: b64u(container),
    },
    grant: {
      code,
      joinerPriv: b64u(joiner.priv),
      joinerPub: b64u(joiner.pub),
      granterPriv: b64u(granter.priv),
      granterPub: b64u(granter.pub),
      nonce: b64u(grantNonce),
      box,
    },
  };
}

const vectors = await build();

// Every vector must also round-trip through the opening side.
const opened = await openFile(roomKey, vectors.file.salt, vectors.file.encMeta);
if (JSON.stringify(opened.meta) !== JSON.stringify(meta)) throw new Error("openFile did not round-trip");
const joiner = { priv: joinerPriv, pub: fromB64u(vectors.grant.joinerPub) };
const k = await acceptGrant(code, joiner, vectors.grant.granterPub, vectors.grant.box, vectors.kid);
if (b64u(k) !== vectors.roomKey) throw new Error("acceptGrant did not round-trip");
await acceptGrant("OTHER", joiner, vectors.grant.granterPub, vectors.grant.box, vectors.kid).then(
  () => {
    throw new Error("a grant opened under the wrong room code");
  },
  () => {},
);
const chunks: Uint8Array[] = [];
await decryptStream(new Blob([fromB64u(vectors.file.container)]).stream(), fromB64u(vectors.file.fileKey), (c) => {
  chunks.push(c);
});
if (b64u(new Uint8Array(await new Blob(chunks).arrayBuffer())) !== vectors.file.plaintext) {
  throw new Error("BSE2 container did not round-trip");
}

const json = JSON.stringify(vectors, null, 2) + "\n";
if (process.argv.includes("--check")) {
  const current = fs.readFileSync(OUT, "utf8");
  if (current !== json) {
    console.error("room-e2e-vectors.json drifted from src/lib/rooms/e2e.ts");
    process.exit(1);
  }
  console.log("room e2e vectors: OK (round-trips + byte-identical)");
} else {
  fs.writeFileSync(OUT, json);
  console.log(`wrote ${path.relative(process.cwd(), OUT)}`);
}
